### ISSUE TITLE
Typeo

### ISSUE THREAD

**Issue by wjczf123** [amazon-research/sentence-representations#3]
1. The Eq. (7) in Virtual Augmentation Supported Contrastive Learning of Sentence Representations contradicts 'small values of l_{align} ....'.

2. StackOverflow and CLINC150 (see Tables 4 and ??)

3. Eq. (9) and Figure 3(b) also seems coufused. l_{intra} should be negative in Figure 3(b).

**Comment by Dejiao2018** [comment]
Thank you for the comments. We have updated our paper draft and released the code.

**Comment by wjczf123** [comment]
OK. Thank you for your reply.
